version: "3.9"
services:
  web:
    image: malberti/trails-app
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile.web
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      PORT: 5000
      DATABASE_URL: postgresql://postgres:postgres@db:5432/trails_app
  db:
    image: "postgres:latest"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=trails_app
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
