defaults:
  - _self_ #configs from the Defaults List are overriding config.yaml
  - flask@_global_: ${oc.env:FLASK_ENV}
  - server: ${oc.env:FLASK_ENV}
  - override hydra/job_logging: custom
#  - _self_ #config.yaml is overriding configs from the Defaults List

hydra:
  # disable changing of cwd as it interferes with flask auto-restart
  run:
    dir: .
  # output files creation
  output_subdir: null
